apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'io.fabric'


android {
    signingConfigs {
        config {
            keyAlias 'key0'
            keyPassword '457BWY4z'
            storeFile file('/Users/sergej/doramatv_key')
            storePassword '457BWY4z'
        }
    }
    compileSdkVersion 28
    defaultConfig {
        applicationId "ru.garretech.garred.doramatv"
        minSdkVersion 19
        targetSdkVersion 28
        versionCode 24
        versionName "1.4.2"
        multiDexEnabled true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
        signingConfig signingConfigs.config
    }
    buildTypes {
        debug {
            ext.enableCrashlytics = false
        }

        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.config
        }
    }
    productFlavors {
    }
    buildToolsVersion '28.0.3'
    compileOptions {
        sourceCompatibility = '1.8'
        targetCompatibility = '1.8'
    }
}


ext {
    supportLibVersion = "28.0.0"
    archComponentsVersion = "1.1.1"
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:multidex:1.0.3'

    implementation "com.android.support:design:$supportLibVersion"
    implementation "com.android.support:customtabs:$supportLibVersion"
    implementation "com.android.support:recyclerview-v7:$supportLibVersion"

    implementation "android.arch.persistence.room:runtime:$archComponentsVersion"
    implementation "android.arch.persistence.room:rxjava2:$archComponentsVersion"

    implementation 'com.squareup.okhttp3:okhttp:3.14.1'

    implementation 'org.jsoup:jsoup:1.11.3'

    implementation 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.46'

    implementation 'io.reactivex.rxjava2:rxjava:2.2.8'
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'

    implementation 'com.android.support:support-v4:28.0.0'
    kapt "android.arch.persistence.room:compiler:$archComponentsVersion"
    annotationProcessor "android.arch.persistence.room:compiler:$archComponentsVersion"

    debugImplementation 'im.dino:dbinspector:3.4.1@aar'

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    implementation 'com.yandex.android:mobmetricalib:3.5.3'
    implementation 'com.yandex.android:mobileads:2.81'


    implementation('com.crashlytics.sdk.android:crashlytics:2.9.9@aar') {
        transitive = true;
    }

    testImplementation 'junit:junit:4.12'
}
repositories {
    mavenCentral()
    maven { url 'https://maven.fabric.io/public' }
}
